### ISSUE TITLE
editorconfig is unecessary when you have prettier

### ISSUE THREAD

**Issue by Xerios** [nathsou/poy#8]
At first I had the impression that most editors supported the editorconfig file by default, unfortunately that's not the case. For instance, vscode requires an extension to support editorconfig.

Prettier is great but it is as they say "opinionated" and unfortunately not very customizable.
Personally I use [eslint stylistic](https://eslint.style/) with eslint + import + typescript plugins, which allows a more fine-tuned control over the style while still providing all the warnings and error-checking.

It takes time to setup a proper config matching prettier, so here's mine if you're interested:
https://gist.github.com/Xerios/efa3a230629d92a537efb866b24f7987

Otherwise if you don't want to mess with formatting, you can simply remove editorconfig and keep prettier config

**Comment by nathsou** [comment]
Thanks for sharing your config, for now I'm okay with the opinionated style from prettier.
I experimented with editorconfig but it doesn't support a lot of options so I went with prettier instead and forgot to remove it.
In my last commit, I removed the editorconfig file and switched to 2 spaces instead of 4 as I'm now more used to it compared to when I started the project.
